# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Form(object):
    def setupUi(self, Login_Form):
        Login_Form.setObjectName("Login_Form")
        Login_Form.resize(561, 549)
        Login_Form.setStyleSheet("*{\n"
"font-family:century gothic;\n"
"font-size:24px;\n"
"}\n"
"\n"
"QFrame\n"
"{\n"
"background:rgba(0,0,0,0.8);\n"
"border-radius:15px;\n"
"}\n"
"#Login_Form\n"
"{\n"
"background:url(:/pic/Login_bg.jfif);\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background:red;\n"
"border-radius:60px;\n"
"}\n"
"\n"
"QToolButton\n"
"{\n"
"background:red;\n"
"border-radius:60px;\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"color:white;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"color:#333;\n"
"border-radius:15px;\n"
"background:#49ebff;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}\n"
"\n"
"#label_login_error\n"
"{\n"
"color:red;\n"
"font-size:12px;\n"
"}")
        self.frame = QtWidgets.QFrame(Login_Form)
        self.frame.setGeometry(QtCore.QRect(60, 80, 441, 441))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(150, 60, 161, 31))
        self.label.setObjectName("label")
        self.pushButton_login = QtWidgets.QPushButton(self.frame)
        self.pushButton_login.setGeometry(QtCore.QRect(50, 360, 351, 51))
        self.pushButton_login.setObjectName("pushButton_login")
        self.lineEdit_username = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_username.setGeometry(QtCore.QRect(60, 160, 341, 31))
        self.lineEdit_username.setText("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_password.setGeometry(QtCore.QRect(60, 270, 341, 31))
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 161, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(60, 230, 161, 31))
        self.label_3.setObjectName("label_3")
        self.label_login_error = QtWidgets.QLabel(self.frame)
        self.label_login_error.setGeometry(QtCore.QRect(130, 325, 185, 15))
        self.label_login_error.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_login_error.setText("")
        self.label_login_error.setObjectName("label_login_error")
        self.toolButton = QtWidgets.QToolButton(Login_Form)
        self.toolButton.setGeometry(QtCore.QRect(220, 10, 121, 121))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("登录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(128, 128))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Login_Form)
        QtCore.QMetaObject.connectSlotsByName(Login_Form)

    def retranslateUi(self, Login_Form):
        _translate = QtCore.QCoreApplication.translate
        Login_Form.setWindowTitle(_translate("Login_Form", "Form"))
        self.label.setText(_translate("Login_Form", "LOGIN HERE"))
        self.pushButton_login.setText(_translate("Login_Form", "Login"))
        self.lineEdit_username.setPlaceholderText(_translate("Login_Form", "Username"))
        self.lineEdit_password.setPlaceholderText(_translate("Login_Form", "Password"))
        self.label_2.setText(_translate("Login_Form", "Username"))
        self.label_3.setText(_translate("Login_Form", "Password"))
import pictures.pic_rc
